apiVersion: v1
kind: Namespace
metadata:
  name: stack-elk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeatconfigmap
  namespace: stack-elk
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
      - '/var/lib/docker/containers/*/*.log'

    output.kafka:
      hosts: ["kafka-deployment:9092"]
      topic: "logs"
      codec.format:
        string: '%{[@timestamp]} %{[message]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-deployment
  namespace: stack-elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
        - name: filebeat
          image: elastic/filebeat:7.14.0
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: filebeatconfig
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml

            - name: logcontainer
              mountPath: /var/lib/docker/containers
      volumes:
        - name: filebeatconfig
          configMap:
            name: filebeatconfigmap
        - name: logcontainer
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: v1
kind: Service
metadata:
  name: filebeat-deployment
  namespace: stack-elk
spec:
  type: ClusterIP
  selector:
    app: filebeat
  ports:
    - port: 5044
