apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: stack-elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper
          ports:
            - containerPort: 2181
          env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"


---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-deployment
  namespace: stack-elk
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
