apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-deployment
  namespace: stack-elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: bitnami/elasticsearch:7.17.0
          ports:
          - containerPort: 9200
          env:
          - name: cluster.name
            value: "local"
          - name: bootstrap.memory_lock
            value: "true"
          - name: discovery.type
            value: "single-node"
          - name: xpack.security.enabled
            value: "false"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: ELASTICSEARCH_URL
            value: "http://elasticsearch:9200"

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: stack-elk
spec:
  type: NodePort
  selector:
    app: elastic
  ports:
    - name: http
      port: 9200
      targetPort: 9200
