apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: stack-elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka
          ports:
          - containerPort: 9092
          env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-deployment:2181"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-deployment:9092"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT:PLAINTEXT"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-deployment
  namespace: stack-elk
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
