apiVersion: v1
kind: ConfigMap
metadata:
  name: logstashconfigmap
  namespace: stack-elk
data:
  logstash.conf: |
    input {
      kafka {
         bootstrap_servers => "http://kafka-deployment:9092"
         topics => ["logs"]
      }
    }

    output {
      elasticsearch {
         hosts => ["elasticsearch:9200"]
         index => "log-%{+YYY.MM.dd}"
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  namespace: stack-elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:8.8.1
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: logstashconfig
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
      volumes:
        - name: logstashconfig
          configMap:
            name: logstashconfigmap
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-deployment
  namespace: stack-elk
spec:
  type: ClusterIP
  ports:
  -  port: 9600
  selector:
    app: logstash
